// Command mkinf generates a branded hidriver.inf for the loki virtual HID
// driver from a small set of fields (supports Chinese via UTF-16LE output and an
// optional zh-CN [Strings.0804] section).
//
// Usage:
//
//	mkinf -out hidriver.inf -device "Loki 虚拟键鼠" -disk "Loki 安装盘" \
//	      -provider hkloudou -manufacturer hkloudou -service "Loki HID Service"
//
// or with a JSON config (flags override JSON fields that are set):
//
//	mkinf -config branding.json -out hidriver.inf
//
// The .sys binary is unaffected by branding, but changing the INF invalidates
// the driver catalog (.cat): re-run inf2cat + signtool after generating (for
// test signing), or pick branding before a one-time Microsoft attestation
// submission.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strings"
	"unicode/utf16"
)

// Branding holds the fillable INF display strings.
type Branding struct {
	DeviceName       string            `json:"deviceName"`
	DiskName         string            `json:"diskName"`
	ProviderName     string            `json:"providerName"`
	ManufacturerName string            `json:"manufacturerName"`
	ServiceName      string            `json:"serviceName"`
	ClassName        string            `json:"className"`
	DriverVer        string            `json:"driverVer"`
	ZhCN             map[string]string `json:"zhCN"` // optional per-field zh-CN overrides
}

// defaults keep the tool runnable with no arguments and consistent with the
// checked-in driver.
func defaults() Branding {
	return Branding{
		DeviceName:       "Loki Virtual HID",
		DiskName:         "Loki Install Disk",
		ProviderName:     "hkloudou",
		ManufacturerName: "hkloudou",
		ServiceName:      "Loki HID Service",
		ClassName:        "HIDRIVER",
		DriverVer:        "10/10/2021",
	}
}

// infBody is everything before [Strings]; the %tokens% are resolved by Windows
// from the [Strings] sections this tool appends.
const infBody = `[Version]
Signature="$WINDOWS NT$"
Class=%ClassName%
ClassGuid={78A1C341-4539-11d3-B88D-00C04FAD5171}
Provider=%ProviderName%
CatalogFile=hidriver.cat
DriverVer=%DriverVerValue%

[ClassInstall32]
Addreg=ClassReg
[ClassReg]
HKR,,,0,%ClassName%
HKR,,Icon,,-24

[SourceDisksNames]
1=%DiskName%,,,
[SourceDisksFiles]
hidriver.sys=1
[DestinationDirs]
DefaultDestDir=12

[Manufacturer]
%ManufacturerName%=Microsoft,NT$ARCH$.6.1
[Microsoft.NT$ARCH$.6.1]
%DeviceName%=MyInstall,root\hidriver

[MyInstall.NT]
CopyFiles=Files
[Files]
hidriver.sys

[MyInstall.NT.HW]
AddReg=HWAddReg
[HWAddReg]
HKR,,"LowerFilters",0x00010008,"hidriver"

[MyInstall.NT.Services]
AddService=hidriver,0x00000000,hidriverService
AddService=mshidkmdf,0x00000002,mshidkmdfService
[hidriverService]
DisplayName=%ServiceName%
ServiceType=1
StartType=3
ErrorControl=1
ServiceBinary=%12%\hidriver.sys
[mshidkmdfService]
ServiceType=1
StartType=3
ErrorControl=1
ServiceBinary=%12%\mshidkmdf.sys

[MyInstall.NT.Wdf]
KmdfService=hidriver,KmdfLibrary
[KmdfLibrary]
KmdfLibraryVersion=$KMDFVERSION$
`

func infEscape(s string) string {
	// In INF strings, a literal double quote is doubled.
	return strings.ReplaceAll(s, `"`, `""`)
}

func isASCII(s string) bool {
	for _, r := range s {
		if r > 0x7f {
			return false
		}
	}
	return true
}

func buildINF(b Branding) (string, error) {
	if b.ClassName == "" {
		b.ClassName = "HIDRIVER"
	}
	if b.DriverVer == "" {
		b.DriverVer = defaults().DriverVer
	}
	for name, v := range map[string]string{
		"deviceName": b.DeviceName, "diskName": b.DiskName,
		"providerName": b.ProviderName, "manufacturerName": b.ManufacturerName,
		"serviceName": b.ServiceName,
	} {
		if strings.TrimSpace(v) == "" {
			return "", fmt.Errorf("field %q is required", name)
		}
	}

	var sb strings.Builder
	// Header comment records the device paths the user-mode lib must use.
	fmt.Fprintf(&sb, "; Generated by cmd/mkinf. Class=%s\n", b.ClassName)
	fmt.Fprintf(&sb, "; user-mode device paths: mouse=\\\\?\\HID#%s&Col02#1  keyboard=\\\\?\\HID#%s&Col04#1\n\n", b.ClassName, b.ClassName)

	body := strings.ReplaceAll(infBody, "%DriverVerValue%", b.DriverVer)
	sb.WriteString(body)

	// Neutral [Strings].
	sb.WriteString("\n[Strings]\n")
	fmt.Fprintf(&sb, "DeviceName=\"%s\"\n", infEscape(b.DeviceName))
	fmt.Fprintf(&sb, "DiskName=\"%s\"\n", infEscape(b.DiskName))
	fmt.Fprintf(&sb, "ProviderName=\"%s\"\n", infEscape(b.ProviderName))
	fmt.Fprintf(&sb, "ManufacturerName=\"%s\"\n", infEscape(b.ManufacturerName))
	fmt.Fprintf(&sb, "ServiceName=\"%s\"\n", infEscape(b.ServiceName))
	fmt.Fprintf(&sb, "ClassName=\"%s\"\n", infEscape(b.ClassName))

	// Optional zh-CN section (LangID 0804). Only tokens present are overridden;
	// the rest fall back to the neutral [Strings].
	if len(b.ZhCN) > 0 {
		sb.WriteString("\n[Strings.0804]\n")
		order := []struct{ key, token string }{
			{"deviceName", "DeviceName"}, {"diskName", "DiskName"},
			{"providerName", "ProviderName"}, {"manufacturerName", "ManufacturerName"},
			{"serviceName", "ServiceName"}, {"className", "ClassName"},
		}
		for _, o := range order {
			if v, ok := b.ZhCN[o.key]; ok && strings.TrimSpace(v) != "" {
				fmt.Fprintf(&sb, "%s=\"%s\"\n", o.token, infEscape(v))
			}
		}
	}
	return sb.String(), nil
}

// needsUTF16 reports whether any content requires a Unicode INF.
func (b Branding) needsUTF16() bool {
	if !isASCII(b.DeviceName) || !isASCII(b.DiskName) || !isASCII(b.ProviderName) ||
		!isASCII(b.ManufacturerName) || !isASCII(b.ServiceName) || !isASCII(b.ClassName) {
		return true
	}
	for _, v := range b.ZhCN {
		if !isASCII(v) {
			return true
		}
	}
	return false
}

// encodeUTF16LE returns UTF-16LE bytes with a BOM and CRLF line endings, which
// is what Windows expects for a Unicode INF.
func encodeUTF16LE(s string) []byte {
	s = strings.ReplaceAll(s, "\r\n", "\n")
	s = strings.ReplaceAll(s, "\n", "\r\n")
	u := utf16.Encode([]rune(s))
	out := make([]byte, 0, 2+len(u)*2)
	out = append(out, 0xFF, 0xFE) // BOM
	for _, c := range u {
		out = append(out, byte(c), byte(c>>8))
	}
	return out
}

func encodeCRLF(s string) []byte {
	s = strings.ReplaceAll(s, "\r\n", "\n")
	s = strings.ReplaceAll(s, "\n", "\r\n")
	return []byte(s)
}

func main() {
	var (
		configPath = flag.String("config", "", "path to a JSON branding file (optional)")
		out        = flag.String("out", "hidriver.inf", "output INF path (\"-\" for stdout)")
	)
	b := defaults()
	flag.StringVar(&b.DeviceName, "device", b.DeviceName, "DeviceName (shown in Device Manager)")
	flag.StringVar(&b.DiskName, "disk", b.DiskName, "DiskName (install prompt)")
	flag.StringVar(&b.ProviderName, "provider", b.ProviderName, "ProviderName")
	flag.StringVar(&b.ManufacturerName, "manufacturer", b.ManufacturerName, "ManufacturerName")
	flag.StringVar(&b.ServiceName, "service", b.ServiceName, "ServiceName (service display name)")
	flag.StringVar(&b.ClassName, "class", b.ClassName, "ClassName (KEEP as HIDRIVER unless you also change the lib device paths)")
	flag.StringVar(&b.DriverVer, "driverver", b.DriverVer, "DriverVer date, MM/DD/YYYY")
	flag.Parse()

	// Merge JSON config first, then let explicitly-set flags win.
	if *configPath != "" {
		raw, err := os.ReadFile(*configPath)
		if err != nil {
			fmt.Fprintln(os.Stderr, "mkinf: read config:", err)
			os.Exit(1)
		}
		var fromJSON Branding
		if err := json.Unmarshal(raw, &fromJSON); err != nil {
			fmt.Fprintln(os.Stderr, "mkinf: parse config:", err)
			os.Exit(1)
		}
		merged := fromJSON
		flag.Visit(func(f *flag.Flag) {
			switch f.Name {
			case "device":
				merged.DeviceName = b.DeviceName
			case "disk":
				merged.DiskName = b.DiskName
			case "provider":
				merged.ProviderName = b.ProviderName
			case "manufacturer":
				merged.ManufacturerName = b.ManufacturerName
			case "service":
				merged.ServiceName = b.ServiceName
			case "class":
				merged.ClassName = b.ClassName
			case "driverver":
				merged.DriverVer = b.DriverVer
			}
		})
		// Fill any still-empty required-ish fields from defaults.
		d := defaults()
		if merged.ClassName == "" {
			merged.ClassName = d.ClassName
		}
		if merged.DriverVer == "" {
			merged.DriverVer = d.DriverVer
		}
		b = merged
	}

	if b.ClassName != "HIDRIVER" {
		fmt.Fprintf(os.Stderr,
			"mkinf: WARNING: ClassName=%q differs from HIDRIVER; the user-mode lib finds the device via\n"+
				"        \\\\?\\HID#%s&Col02#1 (mouse) and &Col04#1 (keyboard). Update windows/lib/mouse.cpp\n"+
				"        and keyboard.cpp to match, or the DLL will not find the device.\n",
			b.ClassName, b.ClassName)
	}

	text, err := buildINF(b)
	if err != nil {
		fmt.Fprintln(os.Stderr, "mkinf:", err)
		os.Exit(1)
	}

	var data []byte
	if b.needsUTF16() {
		data = encodeUTF16LE(text)
	} else {
		data = encodeCRLF(text)
	}

	if *out == "-" {
		os.Stdout.Write(data)
		return
	}
	if err := os.WriteFile(*out, data, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "mkinf: write:", err)
		os.Exit(1)
	}
	enc := "ASCII/CRLF"
	if b.needsUTF16() {
		enc = "UTF-16LE+BOM"
	}
	fmt.Fprintf(os.Stderr, "mkinf: wrote %s (%s). Remember to regenerate & re-sign hidriver.cat.\n", *out, enc)
}
